// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0c4FC501-xfG_oEhn1uc_Rw2I3ZDTbxw',
    appId: '1:1045845374507:web:d40b7cc050208fc5365c6e',
    messagingSenderId: '1045845374507',
    projectId: 'foodordering-ec7f6',
    authDomain: 'foodordering-ec7f6.firebaseapp.com',
    storageBucket: 'foodordering-ec7f6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVwlQ8nMKJxRlLY_OAU-bi70FmWNZrdPc',
    appId: '1:1045845374507:android:be4811d7f3afdfa9365c6e',
    messagingSenderId: '1045845374507',
    projectId: 'foodordering-ec7f6',
    storageBucket: 'foodordering-ec7f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsNH8ajqJLygU24UFJCR08WO1sggrKnN8',
    appId: '1:1045845374507:ios:d30007e19143ffd9365c6e',
    messagingSenderId: '1045845374507',
    projectId: 'foodordering-ec7f6',
    storageBucket: 'foodordering-ec7f6.appspot.com',
    iosClientId: '1045845374507-9oai94mlkussh11ku1ij9eh5m7ovmvs5.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodordering',
  );
}
